### ISSUE TITLE
import - Attribute Error - 'FLET_APP'

### ISSUE THREAD

**Issue by zbooze** [SKbarbon/flet_multi_page#3]
Added Lines per the example.py ..

import flet
from flet_multi_page import subPage

Using VSC - when run->start debugging .... 

module 'flet' has no attribute 'FLET_APP' 
![SubPageError](https://github.com/user-attachments/assets/1aa232ea-aa95-4a9f-951d-eb83a390aed6)

**Comment by thalyssrx** [comment]
AppView before FLET_APP on subpage.py archive.
C:\Users\Your-User\AppData\Roaming\Python\Python312\site-packages\flet_multi_page\subpage.py

https://github.com/user-attachments/assets/b2e1e9b6-3f2c-454a-aa3b-2f189c7e2054

**Comment by zbooze** [comment]
Thank You !! .... made the change and it works GREAT !! ... Appreciated ..
